#!/bin/sh
#
# Bootstrap the SimplePost configure script with GNU autotools.
#
# Copyright (C) 2015-2016 Karl Lenz.  All rights reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 021110-1307, USA.
#

###############################################################################
# Utility Functions
###############################################################################

## Is version one less than or equal to version two?
verlte()
{
	[ "$1" = "$(echo $1'='$2 | tr '=' '\n' | sort -V | head -n 1)" ]
}

###############################################################################
# Environment Configuration
###############################################################################

## Get the minimum autoconf version required for bootstrap.
env_get_ac_prereq()
{
	if [ ! -e configure.ac ]; then
		echo "Error: Missing configure.ac" 1>&2
		exit 1
	fi

	ac_prereq=$(cat configure.ac | grep AC_PREREQ | head -n 1 | grep -Eo '([0-9]+\.)[0-9]+')
	if [ "x$ac_prereq" = "x" ]; then
		echo "Error: Failed to get AC_PREREQ from configure.ac" 1>&2
		exit 1
	fi
}

## Try to find an appropriate autoreconf to bootstrap.
env_find_ac()
{
	env_get_ac_prereq
	echo -n "checking for autoreconf... " 1>&2
	unset ac
	for __file in $(echo $PATH | tr ':' ' '); do
		if [ ! -d $__file ]; then
			continue
		fi

		for __ac in $(find $__file -executable -name 'autoreconf*'); do
			__ac_ver=$($__ac --version | grep -Eo '([0-9]+\.)[0-9]+' | head -n 1)
			if [ "x$__ac_ver" != "x" ] && verlte $ac_prereq $__ac_ver; then
				ac=$__ac
				break
			fi
		done
	done
	if [ "x$ac" = "x" ]; then
		echo "not found" 1>&2
		exit 1
	else
		echo "$__ac_ver" 1>&2
	fi
}

## Get a space-delmited list of the automake macro files required to bootstrap.
env_get_m4_req()
{
	__autoconf_archive_url='http://mirrors.ocf.berkeley.edu/gnu/autoconf-archive/autoconf-archive-2015.09.25.tar.xz'

	# Unfortunately this is a hard-coded list. It must be kept up-to-date
	# when automake dependencies are added or dropped.
	m4_req="ax_prog_doxygen.m4:${__autoconf_archive_url}
		ax_compare_version.m4:${__autoconf_archive_url}"
}

## Set the search path for automake macro files.
env_set_m4_path()
{
	unset m4_search_path

	# This function attempts to build the list of directories to search for
	# automake macro files the same way that aclocal itself does. The
	# algorithm is explained in some detail in the automake manual.
	# https://www.gnu.org/software/automake/manual/html_node/Macro-Search-Path.html

	__ac_dir="$($aclocal --print-ac-dir)"
	if [ "x$__ac_dir" = 'x' ]; then
		echo "Error: Cannot determine autoconf macro search path" 1>&2
		exit 1
	fi

	if [ ! -d "${__ac_dir}-${aclocal_ver}" ]; then
		echo "Error: Missing primary autoconf macro search path ${__ac_dir}-${aclocal_ver}" 1>&2
		exit 1
	fi
	m4_search_path="${__ac_dir}-${aclocal_ver}"

	if [ -d "$__ac_dir" ]; then
		m4_search_path="${m4_search_path}:${__ac_dir}"

		if [ -r "$__ac_dir/dirlist" ]; then
			for __file in $(cat $__ac_dir/dirlist); do
				if [ -d $__file ]; then
					m4_search_path="${m4_search_path}:${__file}"
				fi
			done
		fi
	fi

	if [ "x$ACLOCAL_PATH" != 'x' ]; then
		for __file in $(echo $ACLOCAL_PATH | tr ':' '\n'); do
			if [ ! -d $__file ]; then
				continue
			fi

			m4_search_path="${m4_search_path}:${__file}"

			# WORKAROUND: There is a bug is some versions of autoreconf where
			# they neither respect the $ACLOCAL_PATH nor $ACLOCAL_FLAGS
			# environment variables. They do, however, respect the $ACLOCAL
			# environment variable. Therefore we can work around this bug by
			# exporting an appropriate $ACLOCAL with the "-I" flag to include
			# each of the m4 search paths that aclocal would normally read
			# from $ACLOCAL_PATH.
			#
			# Discussion about this bug:
			# https://lists.gnu.org/archive/html/bug-autoconf/2005-03/msg00041.html
			# https://github.com/Homebrew/homebrew/issues/10824
			#
			if [ "x$ACLOCAL" = 'x' ]; then
				export ACLOCAL="$aclocal -I$__file"
			else
				export ACLOCAL="$ACLOCAL -I$__file"
			fi
		done
	fi

	if [ "x$m4_search_path" = 'x' ]; then
		echo "env_set_m4_path: BUG! m4_search_path is still empty?!" 1>&2
		exit 1
	fi
}

## Download an automake macro file from the given URL.
env_download_m4_file()
{
	if [ "x$1" = 'x' ]; then
		echo "env_download_m4_file: BUG! No m4 macro file to find" 1>&2
		exit 1
	fi
	__file="$1"

	if [ "x$2" = 'x' ]; then
		echo "env_download_m4_file: BUG! No URL for $__file" 1>&2
		exit 1
	fi
	__url="$2"

	__downloaded_file_path="$(find $PWD/aclocal -name $__file 2>/dev/null | head -n1)"
	if [ "x$__downloaded_file_path" = 'x' ]; then
		__downloaded_file_name="$(basename $__url)"
		if [ "x$__downloaded_file_name" = 'x' ]; then
			echo "Error: Failed to extract the base file name from $__url" 1>&2
			exit 1
		fi

		case $__downloaded_file_name in
			*.tar.xz)
				__archive_extract_command='tar xJf'
				;;

			*.tar.bz2)
				__archive_extract_command='tar xjf'
				;;

			*.tar.gz|*.tgz)
				__archive_extract_command='tar xzf'
				;;

			*)
				echo "Error: Unknown archive type $__url" 1>&2
				exit 1
				;;
		esac

		if [ ! -d aclocal ] && ! mkdir aclocal; then
			echo "Error: Failed to make the aclocal directory" 1>&2
			exit 1
		fi

		cd aclocal
		if ! wget $__url; then
			echo "Error: Failed to download $__file from $__url" 1>&2
			rm -rf $__downloaded_file_name
			exit 1
		elif ! $__archive_extract_command $__downloaded_file_name; then
			echo "Error: Failed to extract $__file from $__downloaded_file_name" 1>&2
			rm -rf ${__downloaded_file_name}*
			exit 1
		fi
		cd ..

		__downloaded_file_path="$(find $PWD/aclocal -name $__file 2>/dev/null | head -n1)"
		if [ "x$__downloaded_file_path" = 'x' ]; then
			echo "Error: Could not find $__file in the archive downloaded from $__url" 1>&2
			rm -rf ${__downloaded_file_name}*
			exit 1
		fi
	else
		unset __downloaded_file_name
		unset __archive_extract_command
	fi

	__downloaded_file_base_path="$(dirname $__downloaded_file_path)"
	if [ "x$__downloaded_file_base_path" = 'x' ]; then
		echo "Error: Failed to extract the base search path of $__file from $__downloaded_file_path" 1>&2
		if [ "x$__downloaded_file_name" != 'x' ]; then
			rm -rf ${__downloaded_file_name}*
		fi
		exit 1
	fi

	if [ "x$ACLOCAL_PATH" = 'x' ]; then
		export ACLOCAL_PATH="$__downloaded_file_base_path"
	else
		export ACLOCAL_PATH="${ACLOCAL_PATH}:${__downloaded_file_base_path}"
	fi

	# Update $m4_search_path now that $ACLOCAL_PATH has been updated with the
	# new search path.
	env_set_m4_path
}

## Try to find the given automake macro file in the search path.
env_find_m4_file()
{
	if [ "x$1" = 'x' ]; then
		echo "env_find_m4_file: BUG! No m4 macro file to find" 1>&2
		exit 1
	fi
	__file="$1"

	if [ "x$2" = 'x' ]; then
		unset __url
	else
		__url="$2"
	fi

	if [ "x$m4_search_path" = 'x' ]; then
		echo "env_find_m4_file: BUG! No search path for m4 macro files" 1>&2
		exit 1
	fi

	echo -n "checking for ${__file}... " 1>&2
	__file_found=0
	for __path in $(echo $m4_search_path | tr ':' '\n'); do
		if [ -e "${__path}/${__file}" ]; then
			__file_found=1
			break
		fi
	done
	if [ $__file_found -eq 0 ]; then
		if [ $download -eq 0 ] || [ "x$__url" = 'x' ]; then
			echo "not found" 1>&2
			exit 1
		fi

		echo "downloading" 1>&2
		env_download_m4_file $__file $__url
	else
		echo "found" 1>&2
	fi
}

## Try to find the automake macro files required to bootstrap.
env_find_m4_req()
{
	env_set_m4_path
	env_get_m4_req

	for __req_file in $m4_req; do
		__req_file_name=$(echo $__req_file | cut -d: -f1)
		__req_file_url=$(echo $__req_file | cut -d: -f2-)

		env_find_m4_file $__req_file_name $__req_file_url
	done
}

## Get the minimum automake version required for bootstrap.
env_get_am_prereq()
{
	aclocal_prereq=1.11
}

## Try to find an appropriate automake to bootstrap.
env_find_am()
{
	env_get_am_prereq
	echo -n "checking for aclocal... " 1>&2
	unset aclocal
	for __file in $(echo $PATH | tr ':' ' '); do
		if [ ! -d $__file ]; then
			continue
		fi

		for __aclocal in $(find $__file -executable -name 'aclocal*'); do
			__aclocal_ver=$($__aclocal --version | grep -Eo '([0-9]+\.)[0-9]+' | head -n 1)
			if [ "x$__aclocal_ver" != "x" ] && verlte $aclocal_prereq $__aclocal_ver; then
				aclocal=$__aclocal
				aclocal_ver=$__aclocal_ver
				break
			fi
		done
	done
	if [ "x$aclocal" = "x" ]; then
		echo "not found" 1>&2
		exit 1
	else
		echo "$aclocal_ver" 1>&2
	fi
}

###############################################################################
# Actions
###############################################################################

## Cleanup the artifacts generated by bootstrap and configure.
action_clean()
{
	rm -vrf aclocal/
	rm -vf aclocal.m4
	rm -vrf autom4te.cache/
	rm -vrf build-aux/
	rm -vf config.*

	find -type f -executable -name configure -exec rm -vf {} \;
	find -type f -executable -name simplepost -exec rm -vf {} \;

	find -type f -name Makefile -exec rm -vf {} \;
	find -type f -name Makefile.in -exec rm -vf {} \;

	rm -vf INSTALL
	rm -vf src/config.h

	find -type f -name 'stamp-h?' -exec rm -vf {} \;
	find -type f -name '*.o' -exec rm -vf {} \;
	find -type d -name .deps -exec rm -vrf {} \;

	rm -vrf doc/doxygen/
}

## Generate the build scripts from source.
action_generate()
{
	env_find_ac
	env_find_am
	env_find_m4_req

	echo -n "generating configure... " 1>&2
	if $ac --force --install; then
		echo "yes" 1>&2
	else
		echo "no" 1>&2
		exit 1
	fi
}

## Print our help information.
action_help()
{
	echo "Usage: $0 [OPTIONS] [ACTION]

Actions:
  gen|generate             generate the build scripts for SimplePost
  clean                    cleanup the artifacts generated by bootstrap and configure

Options:
  -n, --no-download        do not attempt to automatically download missing automake dependencies
"
}

###############################################################################
# Entry Point
###############################################################################

action='generate'
download=1

# Process command line options
while [ $# -gt 0 ]; do
	case "$1" in
		-n|--no-download)
			download=0
			;;

		--help)
			# This is a special case. Break now to allow the help option to be
			# handled as an action.
			break
			;;

		-*)
			echo "Invalid Option: $1" 1>&2
			exit 1
			;;

		*)
			if [ $# -gt 1 ]; then
				echo "Invalid Option: $1" 1>&2
				exit 1
			else
				# Break now to avoid another shift. Since this is the final
				# command line argument attempt to handle it as an action.
				break
			fi
			;;
	esac
	shift
done

# Process command line actions
while [ $# -gt 0 ]; do
	case "$1" in
		gen|generate)
			action='generate'
			;;

		clean)
			action='clean'
			;;

		help|--help)
			action='help'
			;;

		*)
			echo "Invalid Action: $1" 1>&2
			exit 1
			;;
	esac
	shift
done

action_$action
exit 0
